### getSystemDate
GET http://localhost:8091/api/common/v1/getSystemDate

### getTopics
GET http://localhost:8091/api/common/v1/getTopics?content=simple


### chat
GET http://localhost:8091/api/transform/v1/chat?content=hello


### 角色列表
POST http://localhost:8091/api/transform/v1/getRoles


### 话题列表
GET http://localhost:8091/api/transform/v1/getTopicList