### StudyController

GET http://localhost:8091/api/getProjectName

###
GET http://localhost:8091/api/getPerson


### getAiRoleListPo
GET http://localhost:8091/api/pojo/getAiRoleListPo

### getAiRoleListPo
GET http://localhost:8091/api/pojo/getAiRoleListVo




### =================================== commonController #########################

### getSystemDate
GET http://localhost:8091/api/common/v1/getSystemDate

### getTopics
GET http://localhost:8091/api/common/v1/getTopics?content=simple


### =================================== studyController #########################

### list
GET http://localhost:8091/api/study/list

### getUserById
GET http://localhost:8091/api/study/getUserById?id=200