spring:
  application:
    name: MySpringBootDemo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study_project?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: Abcdef@123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: Abcdef@123456

server:
  port: 8092
  servlet:
    context-path: /api

# mybatis-plus 全局配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    # log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl #关闭sql日志
  global-config:
    db-config:
      # 逻辑删除
      logic-delete-field: deleted  # 全局逻辑删除的实体宇段名，配置后可不用@TableLogic注解 ==>  Preparing: SELECT * ai_topic WHERE deleted=0
      logic-delete-value: 1        # 逻辑已删除
      logic-not-delete-value: 0    # 逻辑未删除

# log
debug: true
logging:
  level:
    com.ueumd.tech: debug